name: CI (backend + frontend)

on:
  pull_request:
    branches:
      - dev

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

     

  frontend:
    name: Frontend (React/TypeScript)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      
