name: CI (backend + frontend)

on:
  pull_request:
    branches:
      - dev

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Lint (golangci-lint)
        run: |
          golangci-lint run ./... | tee lint-backend.txt || true

      - name: Run unit tests
        run: |
          go test ./... -v | tee backend-tests.txt

      - name: Build
        run: |
          go build ./...

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: |
            lint-backend.txt
            backend-tests.txt

  frontend:
    name: Frontend (React/TypeScript)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Lint (if present)
        run: npm run lint --if-present
        working-directory: frontend

      - name: Run tests
        run: npm test -- --watchAll=false || true
        working-directory: frontend

      - name: Build production bundle
        run: npm run build --if-present
        working-directory: frontend

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
